---

  - name: Decommission resource group
    azure_rm_resourcegroup: 
      name: "{{ prefix }}_rg"
      state: "{{ deploy_state }}"
      cert_validation_mode: ignore
      force: true
    delegate_to: localhost
    tags: rg