---
- name: F5 Agility Azure Lab deploy Resource Group and 2 NIC BIG-IP
  hosts: localhost
  connection: local
  gather_facts: no

  environment:
    AZURE_CLIENT_ID:         "{{ azure_client_id }}"
    AZURE_SECRET:            "{{ azure_secret }}"
    AZURE_SUBSCRIPTION_ID:   "{{ azure_subscription_id }}"
    AZURE_TENANT:            "{{ azure_tenant_id }}"
    AZURE_CERT_VALIDATION:   "ignore"
    F5_USER:                 "{{ azure_user }}"
    F5_PASSWORD:             "{{ azure_user_pass }}"
    F5_VALIDATE_CERTS:       "no"
    F5_SERVER:               "{{ bigipMgmtIp }}"
    F5_SERVER_PORT:          443

  vars_files:
    - "group_vars/azure-f5.yml"
    - "group_vars/nsg_rules.yml"

  roles:
    # Retrieve external/public IP used for security group nsg_rules
    - { role: retrieve_ip, tags: [rg,2nic],    when: deploy_state == "present" }
    # creates AZ resource group, vnet, subnets and security groups
    - { role: setup_az_env, tags: rg,   when: deploy_state == "present" }
    # creates ubuntu based application server(s) and installs application using user-data
    - { role: create_app,   tags: app,  when: deploy_state == "present" }
    # creates a standalone BIG-IP
    - { role: bigip_2nic,   tags: 2nic, when: deployment == "2nic" and deploy_state == "present" }
    # creates a Active/Passive BIG-IP cluster
    - { role: bigip_ha,     tags: ha,   when: deployment == "ha" and deploy_state == "present" }
    # setup facts from the BIG-IP deployments
    - { role: setup_facts,  tags: [2nic,vs],   when: deploy_state == "present" }
    # create profiles and monitors
    - { role: setup_profiles, tags: vs,   when: deploy_state == "present" }
    # create application services using an AS3 declaration
    #- { role: create_services, tags: vs, when: deploy_state == "present" }
    # decommision the resource group
    - { role: decom_az_env, tags: rg,   when: deploy_state == "absent"  }

  tasks:
    - debug:
        msg: "BIG-IP can be accessed via https://{{ bigipMgmtIp }}"
      when: deployment == "2nic"
      tags: vs
