---
- name: F5 Agility Azure Lab deploy Resource Group and 2 NIC BIG-IP
  hosts: localhost
  connection: local
  gather_facts: no

  environment:  
    AZURE_CLIENT_ID:         "{{ azure_client_id }}"
    AZURE_SECRET:            "{{ azure_secret }}"
    AZURE_SUBSCRIPTION_ID:   "{{ azure_subscription_id }}"
    AZURE_TENANT:            "{{ azure_tenant_id }}"
    AZURE_CERT_VALIDATION:   "ignore"
    F5_USER:                 "{{ azure_user }}" 
    F5_PASSWORD:             "{{ azure_user_pass }}"
    F5_VALIDATE_CERTS:       "no"
    F5_SERVER:               "{{ bigipMgmtIp }}"
  
  vars_files:
    - "group_vars/azure-f5.yml"
    - "group_vars/nsg_rules.yml"

  roles:
    - { role: setup_az_env, tags: rg,   when: deploy_state == "present" }
    - { role: create_app,   tags: app,  when: deploy_state == "present" }
    - { role: bigip_2nic,   tags: 2nic, when: deployment == "2nic" and deploy_state == "present" }
    - { role: bigip_ha,     tags: ha,   when: deployment == "ha" and deploy_state == "present" }
    - { role: decom_az_env, tags: rg,   when: deploy_state == "absent"  }
  
