---
- name: Create additional virtual services
  hosts: localhost
  connection: local
  gather_facts: no


  environment:
    AZURE_CLIENT_ID:         "{{ azure_client_id }}"
    AZURE_SECRET:            "{{ azure_secret }}"
    AZURE_SUBSCRIPTION_ID:   "{{ azure_subscription_id }}"
    AZURE_TENANT:            "{{ azure_tenant_id }}"
    AZURE_CERT_VALIDATION:   "ignore"
    F5_USER:                 "{{ azure_user }}"
    F5_PASSWORD:             "{{ azure_user_pass }}"
    F5_VALIDATE_CERTS:       "no"
    F5_SERVER:               "{{ bigipMgmtIp }}"

  vars_files:
    - group_vars/azure-f5.yml

  roles:
  # setup facts from the BIG-IP deployments
  - { role: setup_facts }
  # add second virtual server 
  - { role: create_vs2 }
