---
# Create application services using AS3

- set_fact:
    declaration: "{{ lookup('template', 'files/as3_azure_bodgeit.j2' )  }}"

- name: Write out declaration data
  local_action: copy content="{{ declaration |to_nice_json }}" dest="/home/ansible/tmp/as3_azure_{{location}}_{{ vsName }}_output.json"

- debug:
    var: declaration

- name: Deploy an app service configuration
  bigip_appsvcs_extension:
    content: "{{ declaration }}"
    state:   "{{ deploy_state }}"
    validate_certs: no
  delegate_to: localhost
