---

  - name: Create BIG-IP HA Cluster
    azure_rm_deployment:
      state: "{{ deploy_state }}"
      cert_validation_mode: ignore
      resource_group_name: "{{ vnetResGroupName }}"
      location: "{{ location }}"
      template: "{{ lookup('file', 'azuredeploy_5_0.json' ) }}"
      parameters:
        adminUsername:
          value: "{{ azure_user }}"
        adminPassword:
          value: "{{ azure_user_pass }}"
        dnsLabel:
          value: "{{ dnsLabel }}"
        instanceName:
          value: "{{ instanceName }}"
        instanceType:
          value: "{{ instanceType }}"
        imageName:
          value: "{{ imageName }}"
        bigIpVersion:
          value: "{{ bigIpVersion }}"
        licensedBandwidth:
          value: "{{ licensedLimit }}"
        numberOfExternalIps:
          value: "{{ numOfExtIps }}"
        vnetName:
          value: "{{ vnetName }}"
        vnetResourceGroupName:
          value: "{{ vnetResGroupName }}"
        mgmtSubnetName:
          value: "{{ mgmtSubnetName }}"
        mgmtIpAddressRangeStart:
          value: "{{ mgmtIpAddrBigIp1 }}"
        externalSubnetName:
          value: "{{ externalSubnetName }}"
        externalIpSelfAddressRangeStart:
          value: "{{ extIpAddrBigIp1 }}"
        externalIpAddressRangeStart:
          value: "{{ extVipAddr1 }}"
        internalSubnetName:
          value: "{{ internalSubnetName }}"
        internalIpAddressRangeStart:
          value: "{{ intIpAddrBigIp1 }}"
        tenantId:
          value: "{{ azure_tenant_id }}"
        clientId:
          value: "{{ azure_client_id }}"
        servicePrincipalSecret:
          value: "{{ azure_secret}}"
        managedRoutes:
          value: "{{ managedRoutes }}"
        ntpServer:
          value: "{{ ntpServer }}"
        timeZone:
          value: "{{ timeZone }}"
        restrictedSrcAddress:
          value: "*"
        tagValues:
          value: "{{ tagValues }}"
        allowUsageAnalytics:
          value: "Yes"
    tags: create_f5

  - name: Modify BIGIP ext security group
    azure_rm_securitygroup:
      cert_validation_mode: ignore
      name: "{{ dnsLabel }}-ext-nsg"
      rules: "{{ ext_rules }}"
      resource_group: "{{ vnetResGroupName }}"
      state: "{{ deploy_state }}"
