---

  - name: Create BIG-IP 2-NIC Standalone
    azure_rm_deployment:
      state: "{{ deploy_state }}"
      cert_validation_mode: ignore
      resource_group_name: "{{ prefix }}_rg"
      location: "{{ location }}"
      template: "{{ lookup('file', 'azuredeploy_5_0.json') }}"
      parameters:
        adminUsername:
          value: "{{ azure_user }}"
        adminPassword:
          value: "{{ azure_user_pass }}"
        dnsLabel:
          value: "{{ dnsLabel }}"
        instanceName:
          value: "{{ instanceName }}"
        instanceType:
          value: "{{ instanceType }}"
        imageName:
          value: "{{ imageName }}"
        bigIpVersion:
          value: "{{ bigIpVersion }}"
        licensedBandwidth:
          value: "{{ licensedLimit }}"
        numberOfExternalIps:
          value: "{{ numOfExtIps }}"
        vnetName:
          value: "{{ vnetName }}"
        vnetResourceGroupName:
          value: "{{ vnetResGroupName }}"
        mgmtSubnetName:
          value: "{{ mgmtSubnetName }}"
        mgmtIpAddress:
            value: "{{ mgmtIpAddrBigIp1 }}"
        externalSubnetName:
          value: "{{ externalSubnetName }}"
        externalIpAddressRangeStart:
          value: "{{ extIpAddrBigIp1 }}"
        ntpServer:
          value: "{{ ntpServer }}"
        timeZone:
          value: "{{ timeZone }}"
        restrictedSrcAddress:
          value: "*"
        tagValues:
          value: "{{ tagValues }}"
        allowUsageAnalytics:
          value: "Yes"

  - name: Modify BIGIP ext security group
    azure_rm_securitygroup:
      cert_validation_mode: ignore
      name: "{{ dnsLabel }}-ext-nsg"
      rules: "{{ ext_rules }}"
      resource_group: "{{ vnetResGroupName }}"
      state: "{{ deploy_state }}"
