---

  - name: Provision feature modules
    bigip_provision:
      module: "{{ item.name }}"
      level: "{{ item.level }}"
      state: "{{ item.state }}"
    delegate_to: localhost
    loop: "{{ f5Modules }}"
    tags: vs

  - name: Wait for BIG-IP to become ready after module provisioning
    bigip_wait:
      delay: 20
      validate_certs: no
      timeout: 180
    delegate_to: localhost
    tags: vs

  - name: Create HTTP head monitor
    bigip_monitor_http:
      state: "{{ deploy_state }}"
      name: "{{ baseProfileName }}_http_head"
      send: "HEAD / HTTP/1.0\r\n\r\n"
      receive: "HTTP/1.1 200"
      validate_certs: no
    delegate_to: localhost
    tags: vs

  - name: Create HTTPS head monitor
    bigip_monitor_https:
      state: "{{ deploy_state }}"
      name: "{{ baseProfileName }}_https_head"
      send: "HEAD / HTTP/1.0\r\n\r\n"
      receive: "HTTP/1.1 200"
      validate_certs: no
    delegate_to: localhost
    tags: vs

  - name: Create TCP profiles
    bigip_profile_tcp:
      name: "{{ baseProfileName}}-tcp-{{ item }}"
      parent: "f5-tcp-{{ item }}"
    delegate_to: localhost
    loop:
      - lan
      - wan

  - name: Create HTTP profile
    bigip_profile_http:
      name: "{{ baseProfileName }}-http"
      insert_xforwarded_for: yes
      redirect_rewrite: all
    delegate_to: localhost

  - name: Create client SSL profile
    bigip_profile_client_ssl:
      name: "{{ baseProfileName }}-clientssl"
    delegate_to: localhost

  - name: Create oneConnect profile
    bigip_profile_oneconnect:
      name: "{{ baseProfileName }}-oneconnect"
    delegate_to: localhost
    
  - name: Install iRules
    bigip_irule:
      validate_certs: no
      module: ltm
      name: "{{ item.name }}"
      content: "{{ lookup('file',  item.file ) }}"
    delegate_to: localhost
    loop:
      - { name: maint_pg_irule, file: maint_page.irule }
      - { name: bodgeit_irule, file: bodgeit.irule }
    tags: vs
