---

- name: Create a public ip address
  azure_rm_publicipaddress:
    resource_group: "{{ vnetResGroupName }}"
    name: "{{ item.name}}_pip"
    allocation_method: Dynamic
  loop: "{{ appServers }}"


- name: Create network interface
  azure_rm_networkinterface:
    cert_validation_mode: ignore
    name: "{{ item.name }}_inf"
    public_ip_address_name: "{{ item.name }}_pip"
    resource_group: "{{ vnetResGroupName }}"
    security_group_name: "{{ prefix }}_sg_ext"  
    subnet_name: "{{ externalSubnetName }}"
    virtual_network_name: "{{ vnetName }}"
  loop: "{{ appServers }}"

- name: Create Bodgeit VM
  azure_rm_virtualmachine:
    state: "{{ deploy_state }}"
    cert_validation_mode: ignore
    resource_group: "{{ prefix }}_rg"
    location: "{{ location }}"
    name: "{{ item.name }}"
    vm_size: "{{ item.instanceType }}"
    custom_data: "{{ lookup('file', 'bodgeit_user_data.sh') }}"
    admin_username: "{{ azure_user }}"
    admin_password: "{{ azure_user_pass }}"
    ssh_password_enabled: true
    subnet_name: "{{ externalSubnetName }}"
    short_hostname: "{{ item.shortName }}"
    network_interfaces: "{{ item.name }}_inf"
    image:
      offer: UbuntuServer
      publisher: Canonical
      sku: '16.04-LTS'
      version: latest  
    tags: "appName=bodgeit"    
  tags: app
  delegation_to: localhost
  with_items: "{{ appServers }}"
